// Generated by gencpp from file can/control.msg
// DO NOT EDIT!


#ifndef CAN_MESSAGE_CONTROL_H
#define CAN_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace can
{
template <class ContainerAllocator>
struct control_
{
  typedef control_<ContainerAllocator> Type;

  control_()
    : speed(0.0)
    , angle(0.0)  {
    }
  control_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef double _speed_type;
  _speed_type speed;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::can::control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can::control_<ContainerAllocator> const> ConstPtr;

}; // struct control_

typedef ::can::control_<std::allocator<void> > control;

typedef boost::shared_ptr< ::can::control > controlPtr;
typedef boost::shared_ptr< ::can::control const> controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can::control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can::control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can': ['/home/zj/ros_space2/src/can/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can::control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can::control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ceff948a711f5758871c34a34e8560d";
  }

  static const char* value(const ::can::control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ceff948a711f575ULL;
  static const uint64_t static_value2 = 0x8871c34a34e8560dULL;
};

template<class ContainerAllocator>
struct DataType< ::can::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can/control";
  }

  static const char* value(const ::can::control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 speed\n\
float64 angle\n\
";
  }

  static const char* value(const ::can::control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can::control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can::control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can::control_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MESSAGE_CONTROL_H
